import { FC, ReactNode } from 'react';
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/layouts/MainLayout.module.css'
import { Navbar } from '../components/Navbar';

interface Props { 
  children?: ReactNode | undefined
}

export const MainLayout: FC<Props> = ({ children }) => {
  return (
    <div className={styles.container}>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    
    <main className={styles.main}>

        <Navbar />

        {children}
    
    </main>

    <footer>
      <a
        href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
        target="_blank"
        rel="noopener noreferrer"
      >
        Powered by{' '}
        <span className={styles.logo}>
          <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
        </span>
      </a>
    </footer>
  </div>
  )
}
